package io.github.yottabytecrafter.builder;

import io.github.yottabytecrafter.utils.DateTimeUtils;
import org.junit.jupiter.api.Test;

import java.time.Clock;
import java.time.Instant;
import java.time.ZoneId;

import static org.junit.jupiter.api.Assertions.*;
import io.github.yottabytecrafter.utils.StringEscapeUtils;

class ClassBuilderTest {

        @Test
        void shouldBuildMinimalClass() {
            // Given
            ClassBuilder builder = new ClassBuilder("TestClass", "com.example", null);

            // When
            String result = builder
                    .makeClassFinal()
                    .build();

            // Then
            // No class-level Javadoc if addGenerated is not called.
            // String expected =
            //         "package com.example;\n\n" +
            //                 "import javax.annotation.Generated;\n\n" +
            //                 "public final class TestClass {\n\n" +
            //                 "}\n";
            // assertEquals(expected, result); // Original comparison removed

            // New assertions:
            assertTrue(result.contains("package com.example;"));
            assertTrue(result.contains("import javax.annotation.Generated;")); // Should be there by default
            assertTrue(result.contains("@Generated("));
            assertTrue(result.contains("value = \"io.github.yottabytecrafter.PropertiesGeneratorMojo\""));
            assertTrue(result.contains("date = ")); // Check that date attribute is present
            assertFalse(result.contains("comments ="), "Comments attribute should not be present in @Generated for minimal class");
            assertTrue(result.contains("public final class TestClass {"));
            assertFalse(result.contains("Contains constants generated from the properties group"), "Class Javadoc for source file should not be present");
        }

        @Test
        void shouldBuildCompleteClass() {
            // Given
            ClassBuilder builder = new ClassBuilder("Constants", "com.example", "1.8.0");

            // Set fixed time for @Generated annotation
            Instant fixedInstant = Instant.parse("2024-01-15T10:15:30.00Z");
            Clock fixedClock = Clock.fixed(fixedInstant, ZoneId.of("UTC"));
            DateTimeUtils.setClock(fixedClock);

            String javaVersion = System.getProperty("java.version");
            String javaVendor = System.getProperty("java.vendor");

            // When
            String result = builder
                    .addGenerated("config.properties")
                    .makeClassFinal()
                    .addPrivateConstructor()
                    .addConstant("property.one", "PROPERTY_ONE", "value1")
                    .addConstant("property.two", "PROPERTY_TWO", "value2")
                    .build();


            // Then
            String expected =
                    String.format(
                            "package com.example;\n\n" +
                            "import javax.annotation.Generated;\n\n" +
                            "/**\n" +
                            " * Contains constants generated from the properties group: 'config.properties'.\n" +
                            " * <p>\n" +
                            " * This class is automatically generated by the property-constant-maven-plugin.\n" +
                            " * Do not modify this file directly.\n" +
                            " */\n" +
                            "@Generated(\n" +
                            "    value = \"io.github.yottabytecrafter.PropertiesGeneratorMojo\",\n" +
                            "    date = \"2024-01-15T10:15:30\",\n" +
                            "    comments = \"Generated from config.properties, version: 1.8.0, environment: Java %s (%s)\"\n" +
                            ")\n" +
                            "public final class Constants {\n\n" +
                            "    private Constants() {\n" +
                            "        // Prevent instantiation\n" +
                            "    }\n\n" +
                            "    /**\n" +
                            "     * Constant for property key: 'property.one'.\n" +
                            "     */\n" +
                            "    public static final String PROPERTY_ONE = \"value1\";\n\n" +
                            "    /**\n" +
                            "     * Constant for property key: 'property.two'.\n" +
                            "     */\n" +
                            "    public static final String PROPERTY_TWO = \"value2\";\n\n" +
                            "}\n"
                    , javaVersion, javaVendor);
            assertEquals(expected, result);

            // Cleanup
            DateTimeUtils.resetClock();
        }

        @Test
        void shouldHandleSpecialCharactersInConstantValues() {
            // Given
            ClassBuilder builder = new ClassBuilder("SpecialConstants", "com.example", null);

            // When
            String result = builder
                    .makeClassFinal()
                    .addConstant("new.line.key", "NEW_LINE", "line1\nline2")
                    .addConstant("quotes.key", "QUOTES", StringEscapeUtils.escapeJavaString("\"quoted text\""))
                    .addConstant("unicode.key", "UNICODE", "Hello • World")
                    .build();

            // Then
            // No class-level Javadoc as addGenerated was not called
            // New assertions:
            assertTrue(result.contains("package com.example;"));
            assertTrue(result.contains("import javax.annotation.Generated;"));
            assertTrue(result.contains("@Generated("));
            assertTrue(result.contains("value = \"io.github.yottabytecrafter.PropertiesGeneratorMojo\""));
            assertTrue(result.contains("date = ")); // Check that date attribute is present
            assertFalse(result.contains("comments ="), "Comments attribute should not be present in @Generated");
            assertTrue(result.contains("public final class SpecialConstants {"));
            assertFalse(result.contains("Contains constants generated from the properties group"), "Class Javadoc for source file should not be present");
            // Assertions for the actual constants
            assertTrue(result.contains("public static final String NEW_LINE = \"line1\\nline2\";"));
            assertTrue(result.contains("public static final String QUOTES = \"\\\"quoted text\\\"\";"));
            assertTrue(result.contains("public static final String UNICODE = \"Hello • World\";"));
        }

        @Test
        void shouldBuildClassWithOnlyConstants() {
            // Given
            ClassBuilder builder = new ClassBuilder("OnlyConstants", "com.example", null);

            // When
            String result = builder
                    .makeClassFinal()
                    .addConstant("original.key.one", "CONSTANT_ONE", "1")
                    .addConstant("original.key.two", "CONSTANT_TWO", "2")
                    .addConstant("original.key.three", "CONSTANT_THREE", "3")
                    .build();

            // Then
            // No class-level Javadoc as addGenerated was not called
            // New assertions:
            assertTrue(result.contains("package com.example;"));
            assertTrue(result.contains("import javax.annotation.Generated;"));
            assertTrue(result.contains("@Generated("));
            assertTrue(result.contains("value = \"io.github.yottabytecrafter.PropertiesGeneratorMojo\""));
            assertTrue(result.contains("date = ")); // Check that date attribute is present
            assertFalse(result.contains("comments ="), "Comments attribute should not be present in @Generated");
            assertTrue(result.contains("public final class OnlyConstants {"));
            assertFalse(result.contains("Contains constants generated from the properties group"), "Class Javadoc for source file should not be present");
            // Assertions for the actual constants
            assertTrue(result.contains("public static final String CONSTANT_ONE = \"1\";"));
            assertTrue(result.contains("public static final String CONSTANT_TWO = \"2\";"));
            assertTrue(result.contains("public static final String CONSTANT_THREE = \"3\";"));
        }
}